# fly.toml app configuration file generated for hrm-frontend on 2023-04-30T21:50:59+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hrm-frontend"
primary_region = "sin"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
